name: Build and publish pypi package
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install poetry
        run: pip install poetry poetry-core
        shell: bash
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry
          check-latest: true
      - name: Install dependencies
        run: |
          poetry install --no-root
        shell: bash
      - name: Publish PyPi package
        run: |
          poetry publish -p ${{ secrets.PYPI_TOKEN }} --build
        shell: bash
